# Reference: https://github.com/mrgnlabs/anchor-test-action/blob/main/action.yaml
name: "Solana Anchor Dev Env"
author: "Seabed Labs"
description: "Run anything inside a solana dev env with anchor"
branding:
  icon: anchor
  color: blue
inputs:
  command:
    description: "any command that works in your repo"
    required: true
    default: "anchor test"
  workspace_dir:
    description: "workspace directory"
    required: false
    default: "."
runs:
  using: "docker"
  image: "docker://seabedlabs/solana-dev-env:rust-v1.72.0_solana-v1.16.13_anchor-v0.28.0_node-v18.17.1"
  entrypoint: shell-exec
  args:
    - "cd ${{ inputs.workspace_dir }}"
    - "yarn install"
    - "solana-keygen new --no-bip39-passphrase"
    - "${{ inputs.command }}"
